name: Auto Update Bot
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: auto-update
      run: |
        bash ./script/auto-update.sh
