name: Auto Update Bot
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Update
      run: |
        git config --global user.name "Update Bot"
        git config --global user.email "lomot@qq.com"
        bash ./script/auto-update.sh

    - name: Publish Image
      if: ${{env.NEW_VERSION != ''}}
      run: |
        echo "publish ${{ env.NEW_VERSION }}"

    - name: Push Commit
      if: ${{env.NEW_VERSION != ''}}
      run: |
        git config --global user.name "Update Bot"
        # git config --global user.email "lomot@qq.com"
        git add . && git commit -am "update to ${{ env.NEW_VERSION }}"
        git push
        git tag ${{ env.NEW_VERSION }}
        git push --tag

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: Release ${{ env.NEW_VERSION }}
        draft: false
        prerelease: false
