name: Auto Update Bot
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 13 * * *'

jobs:
  check-new-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # - name: set env
    #   run: |
    #     echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: auto-update
      run: |
        bash ./script/auto-update.sh
