name: GitHub-exp CI

on:
  push:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub-exp
      run: |
        echo "everything ok"
        cat VERSION
