name: GitHub-exp CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set env
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: GitHub-exp
      run: |
        echo "everything ok"
        echo "version:" ${{ github.ref }}
        echo "version:" ${{ env.RELEASE_VERSION }}
