name: onTags

on:
  push:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: set tag env
    #   run: |
    #     echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    # - name: set env
    #   run: |
    #     echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
  
    - name: set tag env
      id: meta
      run: echo ::set-output name=tag::${GITHUB_REF:10}
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: GitHub-exp
      env:
        RELEASE_VERSION: ${{ steps.meta.outputs.tag }}
      run: |
        echo "everything ok"
        echo "github.ref: " ${{ github.ref }}
        echo "steps.meta.outputs.tag: " ${{ steps.meta.outputs.tag }}
        echo "env version: " ${{ env.RELEASE_VERSION }}
